### ISSUE TITLE
ch12 #14

### ISSUE THREAD

**Issue by rbx1219** [irisyen115/oophw#3]
https://github.com/irisyen115/oophw/blob/423c838be5f225ee4cce53ba58e5b805185716b2/java12/class14/class14.java#L6

不要讓 16 這個數字憑空生出來，先 indexOf, 判斷有再取吧

**Comment by irisyen115** [comment]
改完了

**Comment by rbx1219** [comment]
indexOf 永遠都能取到合理的值嗎? 不存在 nature 怎麼辦

**Comment by irisyen115** [comment]
indexOf會回傳-1

**Comment by rbx1219** [comment]
那 -1 你還能 substring 嗎?
