### ISSUE TITLE
ch12 #17

### ISSUE THREAD

**Issue by rbx1219** [irisyen115/oophw#5]
https://github.com/irisyen115/oophw/blob/423c838be5f225ee4cce53ba58e5b805185716b2/java12/class17/class17.java#L10

1. 所以 short 連 99999 也可以放?
2. error message 也附一下吧? 然後再來解釋這個  error message 比較恰當?

**Comment by irisyen115** [comment]
改完了

**Comment by rbx1219** [comment]
short 的 range 你要不要上網查一下

**Comment by rbx1219** [comment]
short 的 range 你有看過自己寫了什麼嗎
